version: '3'
services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 3080:8080
    volumes:
      - ./docker/nginx-vhost/laravel.nginx:/bitnami/nginx/conf/vhosts/laravel.conf
      - .:/app
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=laravel_bitnami_emp
      - MARIADB_USER=laravel_bitnami_emp
      - MARIADB_PASSWORD=laravel_bitnami_emp
    volumes:
      - ./docker/data/mariadb:/bitnami
  redis:
    image: bitnami/redis:latest
    ports:
      - 63790:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - .:/app
    links:
      - mailcatcher:mailcatcher
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=laravel_bitnami_emp
      - DB_USERNAME=laravel_bitnami_emp
      - DB_PASSWORD=laravel_bitnami_emp
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    links:
    - redis:redis
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8091:8081     # web interface, hit localhost:8091 to explore redis
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1081:80   # web interface, hit localhost:1080 to see the mails
      - 1025:25   # expose port 1025 so we can send emails from the host machine as well

